version: '3.7'
services: 
  gqlpdsslib-mysql:
    container_name: gqlpdsslib-mysql8
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-dbpassword}
    ports:
      - "${MYSQL_PORT:-3308}:3306"
    platform: linux/x86_64
    volumes:
      - ~/opt/dockerMysql8.0.28:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 60
  gqlpdsslib-php:
    depends_on:
      gqlpdsslib-mysql:
        condition: service_healthy
    container_name: gqlpdsslib-php7.4
    image: jesusabarcag/php-dev:php7.4
    volumes: 
      - ..:/var/www/html
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./commands:/home/commands
    ports: 
      - "${APP_PORT:-8080}:8080"
    entrypoint: sh -c "/home/commands/run.sh"
    restart: "no"
    platform: linux/x86_64
    environment:
      - APP_PORT=${APP_PORT:-8080}